import fs from 'fs';
import path from 'path';
import type { ActivityEntry, DateRange } from './types.js';

function pad(n: number): string {
  return String(n).padStart(2, '0');
}

function formatTime(date: Date): string {
  return `${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

function sourceLabel(entry: ActivityEntry): string {
  switch (entry.source) {
    case 'chatwork':
      return `Chatwork (${entry.roomOrRepo})`;
    case 'github':
      return `GitHub (${entry.roomOrRepo})`;
  }
}

export function buildMarkdown(entries: ActivityEntry[], range: DateRange): string {
  const lines: string[] = [];

  lines.push(`# Activity Log — ${range.label}`);
  lines.push('');
  lines.push(
    `> Generated by auto-activity-logger on ${new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC`,
  );
  lines.push('');

  if (entries.length === 0) {
    lines.push('_No activities recorded for this day._');
    return lines.join('\n');
  }

  // Sort chronologically
  const sorted = [...entries].sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime());

  // Group by hour for readability
  let currentHour = -1;

  for (const entry of sorted) {
    const hour = entry.timestamp.getHours();

    if (hour !== currentHour) {
      if (currentHour !== -1) lines.push('');
      lines.push(`---`);
      lines.push('');
      currentHour = hour;
    }

    lines.push(`## [${formatTime(entry.timestamp)}] ${sourceLabel(entry)}`);
    lines.push('');
    lines.push(`- **${entry.eventType}**: ${entry.summary}`);
    lines.push('');
  }

  // Summary section for NotebookLM / AI ingestion
  lines.push('---');
  lines.push('');
  lines.push('## Summary');
  lines.push('');

  const cwCount = entries.filter((e) => e.source === 'chatwork').length;
  const ghCount = entries.filter((e) => e.source === 'github').length;

  lines.push(`- Chatwork messages: **${cwCount}**`);
  lines.push(`- GitHub events: **${ghCount}**`);
  lines.push(`- Total activities: **${entries.length}**`);
  lines.push('');

  // Repos / rooms touched
  const repos = [...new Set(entries.filter((e) => e.source === 'github').map((e) => e.roomOrRepo))];
  const cwRooms = [...new Set(entries.filter((e) => e.source === 'chatwork').map((e) => e.roomOrRepo))];

  if (repos.length > 0) {
    lines.push(`### GitHub repositories`);
    repos.forEach((r) => lines.push(`- ${r}`));
    lines.push('');
  }

  if (cwRooms.length > 0) {
    lines.push(`### Chatwork rooms`);
    cwRooms.forEach((r) => lines.push(`- ${r}`));
    lines.push('');
  }

  return lines.join('\n');
}

export function saveMarkdown(content: string, outputDir: string, label: string): string {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const filename = `${label}_activity.md`;
  const filePath = path.join(outputDir, filename);
  fs.writeFileSync(filePath, content, 'utf8');
  return filePath;
}
