import fs from 'fs';
import path from 'path';
import type { ActivityEntry, DateRange, ScreenshotEntry } from './types.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function pad(n: number): string {
  return String(n).padStart(2, '0');
}

function formatTime(date: Date): string {
  return `${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

function activitySourceLabel(entry: ActivityEntry): string {
  switch (entry.source) {
    case 'chatwork':
      return `💬 Chatwork (${entry.roomOrRepo})`;
    case 'github':
      return `🐙 GitHub (${entry.roomOrRepo})`;
    case 'gmail':
      return `✉️ Gmail (${entry.roomOrRepo})`;
  }
}

// ---------------------------------------------------------------------------
// Unified timeline
// ---------------------------------------------------------------------------

type TimelineItem =
  | { kind: 'activity'; timestamp: Date; data: ActivityEntry }
  | { kind: 'screenshot'; timestamp: Date; data: ScreenshotEntry };

function buildTimeline(
  activities: ActivityEntry[],
  screenshots: ScreenshotEntry[],
): TimelineItem[] {
  const items: TimelineItem[] = [
    ...activities.map((a) => ({ kind: 'activity' as const, timestamp: a.timestamp, data: a })),
    ...screenshots.map((s) => ({ kind: 'screenshot' as const, timestamp: s.timestamp, data: s })),
  ];
  return items.sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime());
}

// ---------------------------------------------------------------------------
// Section renderers
// ---------------------------------------------------------------------------

function renderActivity(entry: ActivityEntry, lines: string[]): void {
  lines.push(`## [${formatTime(entry.timestamp)}] ${activitySourceLabel(entry)}`);
  lines.push('');
  lines.push(`- **${entry.eventType}**: ${entry.summary}`);
  lines.push('');
}

function renderScreenshot(entry: ScreenshotEntry, lines: string[]): void {
  const matched = entry.matchedActivity;

  if (matched) {
    const matchLabel = activitySourceLabel(matched);
    lines.push(`## [${formatTime(entry.timestamp)}] 📸 Screenshot & ${matchLabel}`);
    lines.push('');
    lines.push(`- **Screenshot:** ${entry.filename}`);

    lines.push(`- **${activitySourceLabel(matched)}:** ${matched.summary}`);

    if (entry.inference) {
      lines.push(`- **推測:** ${entry.inference}`);
    }
  } else {
    lines.push(`## [${formatTime(entry.timestamp)}] 📸 Screenshot`);
    lines.push('');
    lines.push(`- **Screenshot:** ${entry.filename}`);
  }

  lines.push('');
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function buildMarkdown(
  activities: ActivityEntry[],
  range: DateRange,
  screenshots: ScreenshotEntry[] = [],
): string {
  const lines: string[] = [];

  lines.push(`# Activity Log — ${range.label}`);
  lines.push('');
  lines.push(
    `> Generated by auto-activity-logger on ${new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC`,
  );
  lines.push('');

  if (activities.length === 0 && screenshots.length === 0) {
    lines.push('_No activities recorded for this day._');
    return lines.join('\n');
  }

  const timeline = buildTimeline(activities, screenshots);
  let currentHour = -1;

  for (const item of timeline) {
    const hour = item.timestamp.getHours();

    if (hour !== currentHour) {
      if (currentHour !== -1) lines.push('');
      lines.push('---');
      lines.push('');
      currentHour = hour;
    }

    if (item.kind === 'activity') {
      renderActivity(item.data, lines);
    } else {
      renderScreenshot(item.data, lines);
    }
  }

  // Summary section for NotebookLM / AI ingestion
  lines.push('---');
  lines.push('');
  lines.push('## Summary');
  lines.push('');

  const cwCount = activities.filter((e) => e.source === 'chatwork').length;
  const ghCount = activities.filter((e) => e.source === 'github').length;
  const gmailCount = activities.filter((e) => e.source === 'gmail').length;
  const ssCount = screenshots.length;
  const matchedCount = screenshots.filter((s) => s.matchedActivity !== undefined).length;

  lines.push(`- Chatwork messages: **${cwCount}**`);
  lines.push(`- GitHub events: **${ghCount}**`);
  if (gmailCount > 0) lines.push(`- Gmail sent: **${gmailCount}**`);
  if (ssCount > 0) {
    lines.push(`- Screenshots: **${ssCount}** (${matchedCount} matched to activities)`);
  }
  lines.push(`- Total activities: **${activities.length + ssCount}**`);
  lines.push('');

  const repos = [...new Set(activities.filter((e) => e.source === 'github').map((e) => e.roomOrRepo))];
  const cwRooms = [...new Set(activities.filter((e) => e.source === 'chatwork').map((e) => e.roomOrRepo))];

  if (repos.length > 0) {
    lines.push('### GitHub repositories');
    repos.forEach((r) => lines.push(`- ${r}`));
    lines.push('');
  }

  if (cwRooms.length > 0) {
    lines.push('### Chatwork rooms');
    cwRooms.forEach((r) => lines.push(`- ${r}`));
    lines.push('');
  }

  return lines.join('\n');
}

export function saveMarkdown(content: string, outputDir: string, label: string): string {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const filename = `${label}_activity.md`;
  const filePath = path.join(outputDir, filename);
  fs.writeFileSync(filePath, content, 'utf8');
  return filePath;
}
